//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_proba1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineManageEntities : DbContext
    {
        public CineManageEntities()
            : base("name=CineManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dvorana> Dvoranas { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Kategorija> Kategorijas { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Prikazivanje> Prikazivanjes { get; set; }
        public virtual DbSet<Raspored_Prikazivanja> Raspored_Prikazivanja { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
        public virtual DbSet<Rola> Rolas { get; set; }
        public virtual DbSet<Sjedalo> Sjedaloes { get; set; }
        public virtual DbSet<Zauzetost_Sjedala> Zauzetost_Sjedala { get; set; }
        public virtual DbSet<Vrsta_Transakcije> Vrsta_Transakcije { get; set; }
    }
}
