//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_proba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Prikazivanjes = new HashSet<Prikazivanje>();
            this.Rezervacijas = new HashSet<Rezervacija>();
        }
    
        public int film_id { get; set; }
        public string naslov { get; set; }
        public string readtelj { get; set; }
        public string opis { get; set; }
        public int trajanje { get; set; }
        public double cijena { get; set; }
        public int kategorija_kategorija_id { get; set; }
        public int dvorana_dvorana_id { get; set; }
    
        public virtual Dvorana Dvorana { get; set; }
        public virtual Kategorija Kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prikazivanje> Prikazivanjes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
    }
}
