//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_proba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prikazivanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prikazivanje()
        {
            this.Zauzetost_Sjedala = new HashSet<Zauzetost_Sjedala>();
        }
    
        public int prikazuje_se_id { get; set; }
        public int raspored_prikazivanja_idraspored_prikazivanja { get; set; }
        public int film_film_id { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Raspored_Prikazivanja Raspored_Prikazivanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zauzetost_Sjedala> Zauzetost_Sjedala { get; set; }
    }
}
