//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_proba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int rezervacija_id { get; set; }
        public int film_film_id { get; set; }
        public int sjedala_sjedalo_id { get; set; }
        public int korisnik_korisnik_id { get; set; }
        public int raspored_prikazivanja_raspored_prikazivanja_id { get; set; }
        public int vrsta_transakcije_id { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Raspored_Prikazivanja Raspored_Prikazivanja { get; set; }
        public virtual Sjedalo Sjedalo { get; set; }
        public virtual Vrsta_Transakcije Vrsta_Transakcije { get; set; }
    }
}
