//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_proba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sjedalo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sjedalo()
        {
            this.Rezervacijas = new HashSet<Rezervacija>();
            this.Zauzetost_Sjedala = new HashSet<Zauzetost_Sjedala>();
        }
    
        public int sjedalo_id { get; set; }
        public int mjesto { get; set; }
        public string red { get; set; }
        public int dvorana_dvorana_id { get; set; }
    
        public virtual Dvorana Dvorana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zauzetost_Sjedala> Zauzetost_Sjedala { get; set; }
    }
}
